
# *************************************************************************************************************************************************
# --------------------------------------------------------------------------------------------------------------------------------------
# Install CP4WAIOPS PREREQUISITES
# --------------------------------------------------------------------------------------------------------------------------------------
# *************************************************************************************************************************************************

- name: 🛰️  START - CP4WAIOPS CATALOG - ONLINE
  debug: 
    msg="{{ lookup('pipe','date +%d.%m.%Y---%H:%M:%S') }}"


- name: Log
  shell: |
    export MESSAGE="Installing IBM CatalogSource - Online"
    export currentDate=$(date +%Y-%m-%d_%H:%M)
    echo "---------------------------------------------------------------------------------------------------------------------------------------------------" >> ../install_{{current_cp4waiops_feature.kind}}.log
    echo $currentDate" - "$MESSAGE  >> ../install_{{current_cp4waiops_feature.kind}}.log

    cat <<EOF | oc apply -f -
    apiVersion: console.openshift.io/v1
    kind: ConsoleNotification
    metadata:
      name: cp4waiops-notification
    spec:
      backgroundColor: '#ffd500'
      color: '#000'
      location: BannerTop
      text: 'Installing CP4WAIOPS: Module {{ansible_play_name}}'    
    EOF



  ignore_errors: true





# Create IBM Operator Catalog
- name:   🚀 CP4WAIOPS CATALOG - Install IBM Operator Catalog - Online
  kubernetes.core.k8s:
    state: present
    template: ./templates/waiops/1_cat-ibm-catalog.j2







