

- name: 🛰️  START - CREATE FEATURE FLAGS
  debug: 
    msg="{{ lookup('pipe','date +%d.%m.%Y---%H:%M:%S') }}"



- name: Log
  shell: |
    export MESSAGE="Create Feature Flags Definition"
    export currentDate=$(date +%Y-%m-%d_%H:%M)
    echo "---------------------------------------------------------------------------------------------------------------------------------------------------" >> ../install_{{current_cp4waiops_feature.kind}}.log
    echo $currentDate" - "$MESSAGE  >> ../install_{{current_cp4waiops_feature.kind}}.log

    cat <<EOF | oc apply -f -
    apiVersion: console.openshift.io/v1
    kind: ConsoleNotification
    metadata:
      name: cp4waiops-notification
    spec:
      backgroundColor: '#ffd500'
      color: '#000'
      location: BannerTop
      text: 'Installing CP4WAIOPS: Create Feature Flags Definition'    
    EOF



  ignore_errors: true



- name: 🚀 INIT - CREATE FEATURE FLAGS
  shell: |
    cat <<EOF | oc apply -n {{ current_cp4waiops_cluster.project }} -f -
    # https://github.ibm.com/katamari/feature-flags/blob/b1e85bc6e846ede7bf2114602b0558f70293278c/feature-flags-configmap.yaml
    apiVersion: v1
    data:
      # CONNECTORS_AIOPS_IBM_COM_BUNDLE_MANIFESTS: disabled
      # CONNECTORS_AIOPS_IBM_COM_BRIDGE_AUTH_ENABLED: "true"
      IRISCART_1431_LOG_DATA_SELECTION_ENABLED: "true"
      IBM_IR_AI_SEASONALITY_PREVIEW_ENABLED: "true"
      IBM_IR_AI_X_IN_Y_PREVIEW_ENABLED: "true"
      ENABLE_FEEDBACK_LEARNING: "true"
      IRISCART_78_DRIFT_ENABLED: "true"
    kind: ConfigMap
    metadata:
      name: feature-flag-configmap
      namespace: {{ current_cp4waiops_cluster.project }}
    EOF
  register: output_string
  ignore_errors: true
  args:
    executable: /bin/bash


- name: 🟣 INIT - RESULT
  debug: 
    var: output_string.stdout_lines
    verbosity: 1

