
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cp4waiops-story-pusher
  namespace: default
  labels:
      app:  cp4waiops-story-pusher
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  cp4waiops-story-pusher
  template:
    metadata:
      labels:
        app:  cp4waiops-story-pusher
    spec:
      containers:
      - image: niklaushirt/cp4waiops-story-pusher:0.6
        imagePullPolicy: Always
        name: gateway
        command:
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "50m"
            memory: "50Mi"
          limits:
            cpu: "550m"
            memory: "550Mi"
        env:
          - name: DEBUG_ME
            value : "False"
          - name: SEND_DISCORD
            value : "True"
          - name: SEND_MAIL
            value : "False"
          - name: DISCORD_WEBHOOK
            value : "https://discord.com/api/webhooks/1055440591019851827/FHrkzpIxVVY1I5_DqJMimn22iAg2s8r4rTV5cJFgqDHKfjbEUndixrjWJ58FRe091wen"
          - name: MAIL_USER
            value : "toto"
          - name: MAIL_PWD
            value : "toto"
          - name: MIN_RANK
            value : "3"
          - name: POLL_DELAY
            value : "5"
