
# *************************************************************************************************************************************************
# --------------------------------------------------------------------------------------------------------------------------------------
# Install AWX (open source Ansible Tower)
# --------------------------------------------------------------------------------------------------------------------------------------
# *************************************************************************************************************************************************


# --------------------------------------------------------------------------------------------------------------------------------------
# Install AWX
# --------------------------------------------------------------------------------------------------------------------------------------
# Create AWX

- name: 🛰️  START - INSTALL AWX
  debug: 
    msg="{{ lookup('pipe','date +%d.%m.%Y---%H:%M:%S') }}"


- name: Log
  shell: |
    export MESSAGE="Installing AWX"
    export currentDate=$(date +%Y-%m-%d_%H:%M)
    echo "---------------------------------------------------------------------------------------------------------------------------------------------------" >> ../install_{{current_cp4waiops_feature.kind}}.log
    echo $currentDate" - "$MESSAGE  >> ../install_{{current_cp4waiops_feature.kind}}.log
  ignore_errors: true

- name: 🟡🟡🟡  OCP CONSOLE - Create Openshift NOTIFICATION
  shell: |
    cat <<EOF | oc apply -f -
    apiVersion: console.openshift.io/v1
    kind: ConsoleNotification
    metadata:
      name: cp4waiops-notification
    spec:
      backgroundColor: '#ffd500'
      color: '#000'
      location: {{global_config.position_ocp_notifications | default("BannerTop")}}
      text: 'Installing {{current_cp4waiops_feature.kind}} - Installing AWX'    
    EOF
  ignore_errors: true
  when: global_config.create_ocp_notifications | default(true) == true  

  
- name: 🚀 AWX - Create AWX Operator
  kubernetes.core.k8s:
    state: present
    namespace: awx
    src: ./templates/awx/operator-install.yaml
  ignore_errors: true


# --------------------------------------------------------------------------------------------------------------------------------------
# Wait for Operator ready
# --------------------------------------------------------------------------------------------------------------------------------------
- name: 🕦 CHECK -  Wait AWX Operator
  shell: |
    NUM_PODS=$(oc get po -n awx | grep operator| grep 2/2| wc -l)
    echo $NUM_PODS
  register: kubectl_num_pods
  until: kubectl_num_pods.stdout|int >= 1
  retries: 100
  delay: 15


# Create aiops-topology-service-account
- name:   🚀 AWX - Patch default storage class if non defined
  shell: |
    export default=$(oc get storageclass -oyaml|grep "is-default-class"|wc -l|tr -d " ")
    echo $default
    if [ $default -lt 1 ]; then
        echo "Patching"
        kubectl patch storageclass {{ WAIOPS_STORAGE_CLASS_FILE }} -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"true"}}}'
      else
        echo "Patching not needed"
      fi
  ignore_errors: true


- name: 🚀 AWX - Create AWX Instance (while waiting for CP4WAIOPS Installation to progress)
  kubernetes.core.k8s:
    state: present
    namespace: awx
    src: ./templates/awx/awx-deploy-cr.yml
  ignore_errors: true

