
- name: 🛰️  START - LOAD LOG TRAINING DATA
  debug: 
    msg="{{ lookup('pipe','date +%d.%m.%Y---%H:%M:%S') }}"




- name: Log
  shell: |
    export MESSAGE="Load LAD Training Data into ElasticSearch"
    export currentDate=$(date +%Y-%m-%d_%H:%M)
    echo "---------------------------------------------------------------------------------------------------------------------------------------------------" >> ../install_{{current_cp4waiops_feature.kind}}.log
    echo $currentDate" - "$MESSAGE  >> ../install_{{current_cp4waiops_feature.kind}}.log

    cat <<EOF | oc apply -f -
    apiVersion: console.openshift.io/v1
    kind: ConsoleNotification
    metadata:
      name: cp4waiops-notification
    spec:
      backgroundColor: '#ffd500'
      color: '#000'
      location: BannerTop
      text: 'Installing CP4WAIOPS: Module {{ansible_role_name}}'    
    EOF



  ignore_errors: true


- name: 📥 TRAINING LOAD LAD - DELETE EXISTING JOB
  kubernetes.core.k8s:
    state: absent
    namespace: turbonomic
    template: ./templates/training/load-job-logs.j2


- name: 📥 TRAINING LOAD LAD - CREATE CLUSTERROLE
  kubernetes.core.k8s:
    state: present
    namespace: default
    src: ./templates/training/default-clusterrole.yaml
    

- name: 📥 TRAINING LOAD LAD - LOAD ELASTICSEARCH LOG DATA 
  kubernetes.core.k8s:
    state: present
    namespace: turbonomic
    template: ./templates/training/load-job-logs.j2

