apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: awx-xwqwm
  namespace: awx
spec:
  targetNamespaces:
    - awx
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: awx-operator
  namespace: awx
spec:
  channel: alpha
  installPlanApproval: Automatic
  name: awx-operator
  source: community-operators
  sourceNamespace: openshift-marketplace
  startingCSV: awx-operator.v1.2.0
---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: example-awx
  namespace: awx
spec:
  ee_resource_requirements:
    requests:
      cpu: 50m
      memory: 64M
  create_preload_data: true
  route_tls_termination_mechanism: Edge
  garbage_collect_secrets: false
  loadbalancer_port: 80
  no_log: true
  task_resource_requirements:
    requests:
      cpu: 50m
      memory: 128M
  image_pull_policy: IfNotPresent
  projects_storage_size: 8Gi
  auto_upgrade: true
  task_privileged: false
  ipv6_disabled: false
  projects_storage_access_mode: ReadWriteMany
  set_self_labels: true
  web_resource_requirements:
    requests:
      cpu: 50m
      memory: 128M
  projects_persistence: true
  replicas: 1
  admin_user: admin
  loadbalancer_protocol: http
  ingress_type: Route
  projects_use_existing_claim: _No_
  projects_storage_class: aaaaaa