---
# *************************************************************************************************************************************************
# --------------------------------------------------------------------------------------------------------------------------------------
# Create Catalog from CASE
# --------------------------------------------------------------------------------------------------------------------------------------
# *************************************************************************************************************************************************

- name: 🛰️  START - CP4WAIOPS CATALOG - CASE
  debug: 
    msg="{{ lookup('pipe','date +%d.%m.%Y---%H:%M:%S') }}"

- name: Log
  shell: |
    export MESSAGE="Installing IBM CatalogSource - CASE"
    export currentDate=$(date +%Y-%m-%d_%H:%M)
    echo "---------------------------------------------------------------------------------------------------------------------------------------------------" >> ../install_{{current_cp4waiops_feature.kind}}.log
    echo $currentDate" - "$MESSAGE  >> ../install_{{current_cp4waiops_feature.kind}}.log
  ignore_errors: true

- name: 🟡🟡🟡  OCP CONSOLE - Create Openshift NOTIFICATION
  shell: |
    cat <<EOF | oc apply -f -
    apiVersion: console.openshift.io/v1
    kind: ConsoleNotification
    metadata:
      name: cp4waiops-notification
    spec:
      backgroundColor: '#ffd500'
      color: '#000'
      location: {{global_config.position_ocp_notifications | default("BannerBottom")}}
      text: 'Installing {{current_cp4waiops_feature.kind}} - Installing IBM CatalogSource - CASE (this can take some time)'    
    EOF
  ignore_errors: true
  when: global_config.create_ocp_notifications | default(true) == true  




- name: 📥 Create Catalog Source CASE File
  include_tasks: create-catalog-source-case-file.yml

